version: "3.9"
services:
  api-web:
    build: .
    environment:
     - NUM=4000
    ports:
      - "13583:13583"
    networks:
      - nat
    command:
      - "uvicorn"
      - "app.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "13583"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - nat

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - nat

networks:
  nat:
