version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - VERSION=docker
    volumes:
      - ${HOME}/plex:/media/
    restart: always