version: '3'
services:
  client:
    build: client/
    ports:
      - 3000:3000
  server:
    build: server/
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    depends_on:
      - db
