global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "api-web"
    metrics_path: /metrics
    static_configs:
      - targets: ["api-web"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]