global:
  scrape_interval: 10s

# Default metrics_path: /metrics
scrape_configs:
  - job_name: "api-web"
    static_configs:
      - targets: ["localhost:13583"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]