version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - ${HOME}/temp/config:/etc/gitlab
      - ${HOME}/temp/logs:/var/log/gitlab
      - ${HOME}/temp/data:/var/opt/gitlab
    shm_size: '256m'